### ISSUE TITLE
WioLink_xxxxxxというWi-Fiアドレスにも対応させて欲しい

### ISSUE THREAD

**Issue by n0bisuke** [horihiro/wio-setup#1]
Wio_xxxxxxx以外にもWioLink_xxxxxxというWi-Fiアドレスを発信するWio Node（Wio LINKではなく）があるので対応して欲しいです！！

多分製造時のロットによってその辺が少し違うみたいです。

**Comment by horihiro** [comment]
問題のWioNodeで動作検証中。

SSIDチェックを変更することで接続はできるが、AP情報の書き込みに失敗（OKの応答は返ってくる）。
ファームのバージョンをダンプしてみたところ、1.1。

今まで動作検証に使っていた手元のWioNodeのファームは1.2。

**Comment by horihiro** [comment]
0.1.0で、WioNodeファームバージョン1.1に対応したので、SSID「WioLink_XXXXXX」でも設定可能です
